stages:
  - build
  - push
  - deploy

variables:
  KUBE_NAMESPACE: "agent-soc"
  HELM_CHART_DIR: "agent-soc-frontend"

build:
  stage: build
  script:
    - docker build --build-arg NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL" --build-arg NEXT_PUBLIC_ORCHESTRATOR_API_URL="$NEXT_PUBLIC_ORCHESTRATOR_API_URL" --build-arg NEXT_PUBLIC_ENV="$NEXT_PUBLIC_ENV" --build-arg NEXT_PUBLIC_WS_URL="$NEXT_PUBLIC_WS_URL" -t "$HARBOR_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH$CI_PIPELINE_ID" .

  only:
    - develop
  tags:
    - stable

push:
  stage: push
  script:
    - docker push $HARBOR_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH$CI_PIPELINE_ID
  only:
    - develop
  tags:
    - stable

deploy:
  stage: deploy
  tags:
    - stable
  script:
    - helm upgrade --install $HELM_CHART_DIR ./$HELM_CHART_DIR --namespace $KUBE_NAMESPACE --set image.repository="$HARBOR_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME" --set image.tag="$CI_COMMIT_BRANCH$CI_PIPELINE_ID" --kubeconfig=$STAGE_AGENT_SOC_NS
  only:
    - develop
